name: CI

# FIXME: this should be restricted only to master, otherwise concurrent 
# builds in different PRs will overwrite images from each other 
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./builder.Dockerfile
          push: true
          tags: |
            ghcr.io/maxdesiatov/swift-alpine:builder
